[workspace]
members = ["quote_server", "quote_client", "commons", "macros"]
resolver = "2"

[workspace.dependencies]
log="0"
clap = { version = "4", features = ["derive"] }
url="2"
ctrlc = "3"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
