[package]
name = "commons"
version = "0.1.2"
edition = "2024"

[dependencies]
thiserror = "2"
rand = "0"
macros = { path = "../macros" }
log = "0"
simplelog = "0"
serde.workspace = true

[dev-dependencies]
tempfile = "3"
