[package]
name = "quote_client"
version = "0.1.0"
edition = "2024"

[dependencies]
commons = { path = "../commons" }
clap = { version = "4", features = ["derive"] }
tokio.workspace = true
log.workspace = true